### ISSUE TITLE
Support for default wallpapers

### ISSUE THREAD

**Issue by orschiro** [agronick/Wallpaper-Slideshow#1]
Dear @agronick,

Thank you very much for your script! I have one request. It seems that your script requires the user to provide a wallpaper directory:

```
$ ./wallpaper_slideshow.sh 1
./wallpaper_slideshow.sh: line 62: cd: 1: No such file or directory
```

However, personally I am just fine with the default eOS wallpapers and would like to randomise these in a slideshow. Could this be done with your script that if the user does not provide any directory, the script uses the default eOS wallpapers?

Thankfully,

Robert

**Comment by agronick** [comment]
That should be all set now. It was there you just couldn't specify 
minutes as well. Now you can omit the directory and specify minutes.

**Comment by orschiro** [comment]
@agronick 

Thanks for your quick commit! There is still a issue with `realpath`:

```
./wallpaper_slideshow.sh 1
./wallpaper_slideshow.sh: line 69: realpath: command not found
```

**Comment by agronick** [comment]
Hmm I thought that would be a preinstalled command on Elementary. Looks 
like you can do an apt-get install realpath while I find a command that 
works for everyone.

**Comment by agronick** [comment]
I just pushed out a version that uses readlink instead. It should work now.

**Comment by orschiro** [comment]
@agronick 

Works perfectly now. Thanks a lot! :+1:
