### ISSUE TITLE
Wallpaper not changed on login screen

### ISSUE THREAD

**Issue by orschiro** [agronick/Wallpaper-Slideshow#2]
Hi @agronick, 

One small thing I noticed is that while the script changes the desktop wallpaper, it does not change the login screen wallpaper. Can you confirm this? 

Regards,

Robert

**Comment by agronick** [comment]
Yes that is true. I'll look into how they do it and see if I can find a way to make it an option.

**Comment by orschiro** [comment]
That would be great, thanks! :+1:

**Comment by agronick** [comment]
I've looked over the source for pantheon-greater LightDM and looked for a setting in dcomf-editor. I can't see where it is setting it.

**Comment by orschiro** [comment]
@agronick 

Should we report the not changing LightDM background as a bug on the eOS bugtracker on Launchpad?

Personally, I expect LightDM to follow the user-defined wallpaper regardless of whether it is dynamically changing or not.

**Comment by agronick** [comment]
I finally got it working. Its committed. Try it now. I just had to dig around to make it work. You just need qdbus if you don't have it installed.

**Comment by orschiro** [comment]
@agronick 

It seems to work. Thank you very much for digging into this!

Robert

**Comment by agronick** [comment]
No problem. Thanks for using it.
